// Package morphology provides morphological databases for English language analysis.
package morphology

// initializeDatabases loads all morphological databases
func (e *MorphologyEngine) initializeDatabases() {
	e.loadPrefixDatabase()
	e.loadSuffixDatabase()
	e.loadRootWordDatabase()
}

// loadPrefixDatabase initializes the prefix database with common English prefixes
func (e *MorphologyEngine) loadPrefixDatabase() {
	prefixes := map[string]PrefixInfo{
		// Common prefixes with high productivity
		"un": {
			Prefix:       "un",
			Meaning:      "not, opposite of",
			Origin:       "germanic",
			Productivity: 0.9,
			Examples:     []string{"unable", "unknown", "unsafe"},
		},
		"re": {
			Prefix:       "re",
			Meaning:      "again, back",
			Origin:       "latin",
			Productivity: 0.95,
			Examples:     []string{"rebuild", "return", "refresh"},
		},
		"pre": {
			Prefix:       "pre",
			Meaning:      "before",
			Origin:       "latin",
			Productivity: 0.8,
			Examples:     []string{"preload", "prepare", "preview"},
		},
		"dis": {
			Prefix:       "dis",
			Meaning:      "not, opposite of",
			Origin:       "latin",
			Productivity: 0.7,
			Examples:     []string{"disable", "disconnect", "disallow"},
		},
		"mis": {
			Prefix:       "mis",
			Meaning:      "wrongly, badly",
			Origin:       "germanic",
			Productivity: 0.6,
			Examples:     []string{"mistake", "misuse", "mishandle"},
		},
		"over": {
			Prefix:       "over",
			Meaning:      "too much, above",
			Origin:       "germanic",
			Productivity: 0.8,
			Examples:     []string{"override", "overflow", "overload"},
		},
		"under": {
			Prefix:       "under",
			Meaning:      "below, insufficient",
			Origin:       "germanic",
			Productivity: 0.7,
			Examples:     []string{"underflow", "understand", "underline"},
		},
		"out": {
			Prefix:       "out",
			Meaning:      "external, beyond",
			Origin:       "germanic",
			Productivity: 0.75,
			Examples:     []string{"output", "outline", "outside"},
		},
		"in": {
			Prefix:       "in",
			Meaning:      "into, within",
			Origin:       "latin",
			Productivity: 0.85,
			Examples:     []string{"input", "inline", "inside"},
		},
		"auto": {
			Prefix:       "auto",
			Meaning:      "self, automatic",
			Origin:       "greek",
			Productivity: 0.9,
			Examples:     []string{"automatic", "autonomous", "autoload"},
		},
		"multi": {
			Prefix:       "multi",
			Meaning:      "many, multiple",
			Origin:       "latin",
			Productivity: 0.85,
			Examples:     []string{"multiple", "multicast", "multipart"},
		},
		"sub": {
			Prefix:       "sub",
			Meaning:      "under, below",
			Origin:       "latin",
			Productivity: 0.8,
			Examples:     []string{"subtract", "submit", "subclass"},
		},
		"super": {
			Prefix:       "super",
			Meaning:      "above, over",
			Origin:       "latin",
			Productivity: 0.7,
			Examples:     []string{"superior", "superclass", "supervisor"},
		},
		"inter": {
			Prefix:       "inter",
			Meaning:      "between, among",
			Origin:       "latin",
			Productivity: 0.75,
			Examples:     []string{"interface", "interact", "interrupt"},
		},
		"trans": {
			Prefix:       "trans",
			Meaning:      "across, through",
			Origin:       "latin",
			Productivity: 0.7,
			Examples:     []string{"transform", "transmit", "translate"},
		},
		"de": {
			Prefix:       "de",
			Meaning:      "reverse, remove",
			Origin:       "latin",
			Productivity: 0.8,
			Examples:     []string{"debug", "decode", "decrypt"},
		},
		"co": {
			Prefix:       "co",
			Meaning:      "together, with",
			Origin:       "latin",
			Productivity: 0.75,
			Examples:     []string{"connect", "compare", "compile"},
		},
		"anti": {
			Prefix:       "anti",
			Meaning:      "against, opposite",
			Origin:       "greek",
			Productivity: 0.6,
			Examples:     []string{"antivirus", "antipattern", "antisocial"},
		},
		"pseudo": {
			Prefix:       "pseudo",
			Meaning:      "false, fake",
			Origin:       "greek",
			Productivity: 0.5,
			Examples:     []string{"pseudocode", "pseudorandom", "pseudoclass"},
		},
		// Programming-specific prefixes
		"get": {
			Prefix:       "get",
			Meaning:      "retrieve, obtain",
			Origin:       "programming",
			Productivity: 0.95,
			Examples:     []string{"getter", "getValue", "getById"},
		},
		"set": {
			Prefix:       "set",
			Meaning:      "assign, establish",
			Origin:       "programming",
			Productivity: 0.95,
			Examples:     []string{"setter", "setValue", "setDefault"},
		},
		"is": {
			Prefix:       "is",
			Meaning:      "state check, boolean",
			Origin:       "programming",
			Productivity: 0.9,
			Examples:     []string{"isValid", "isEmpty", "isEnabled"},
		},
		"has": {
			Prefix:       "has",
			Meaning:      "possession check",
			Origin:       "programming",
			Productivity: 0.85,
			Examples:     []string{"hasNext", "hasValue", "hasPermission"},
		},
		"can": {
			Prefix:       "can",
			Meaning:      "capability check",
			Origin:       "programming",
			Productivity: 0.8,
			Examples:     []string{"canExecute", "canRead", "canWrite"},
		},
	}
	
	e.prefixDB = prefixes
}

// loadSuffixDatabase initializes the suffix database with common English suffixes
func (e *MorphologyEngine) loadSuffixDatabase() {
	suffixes := map[string]SuffixInfo{
		// Noun-forming suffixes
		"er": {
			Suffix:       "er",
			Meaning:      "one who does",
			Category:     WordCategoryNoun,
			Productivity: 0.95,
			Examples:     []string{"handler", "manager", "worker"},
		},
		"or": {
			Suffix:       "or",
			Meaning:      "one who does",
			Category:     WordCategoryNoun,
			Productivity: 0.8,
			Examples:     []string{"processor", "executor", "validator"},
		},
		"tion": {
			Suffix:       "tion",
			Meaning:      "act or result of",
			Category:     WordCategoryNoun,
			Productivity: 0.9,
			Examples:     []string{"configuration", "validation", "execution"},
		},
		"sion": {
			Suffix:       "sion",
			Meaning:      "act or result of",
			Category:     WordCategoryNoun,
			Productivity: 0.85,
			Examples:     []string{"transmission", "compression", "extension"},
		},
		"ment": {
			Suffix:       "ment",
			Meaning:      "result of action",
			Category:     WordCategoryNoun,
			Productivity: 0.8,
			Examples:     []string{"development", "management", "deployment"},
		},
		"ness": {
			Suffix:       "ness",
			Meaning:      "state or quality",
			Category:     WordCategoryNoun,
			Productivity: 0.85,
			Examples:     []string{"completeness", "readiness", "effectiveness"},
		},
		"ity": {
			Suffix:       "ity",
			Meaning:      "state or quality",
			Category:     WordCategoryNoun,
			Productivity: 0.8,
			Examples:     []string{"security", "reliability", "compatibility"},
		},
		"age": {
			Suffix:       "age",
			Meaning:      "act, result, or state",
			Category:     WordCategoryNoun,
			Productivity: 0.6,
			Examples:     []string{"package", "storage", "usage"},
		},
		"ism": {
			Suffix:       "ism",
			Meaning:      "doctrine or practice",
			Category:     WordCategoryNoun,
			Productivity: 0.5,
			Examples:     []string{"mechanism", "algorithm", "polymorphism"},
		},
		// Adjective-forming suffixes
		"able": {
			Suffix:       "able",
			Meaning:      "capable of being",
			Category:     WordCategoryAdjective,
			Productivity: 0.9,
			Examples:     []string{"readable", "writable", "configurable"},
		},
		"ible": {
			Suffix:       "ible",
			Meaning:      "capable of being",
			Category:     WordCategoryAdjective,
			Productivity: 0.7,
			Examples:     []string{"accessible", "extensible", "compatible"},
		},
		"ed": {
			Suffix:       "ed",
			Meaning:      "past participle",
			Category:     WordCategoryAdjective,
			Productivity: 0.95,
			Examples:     []string{"cached", "encrypted", "validated"},
		},
		"ing": {
			Suffix:       "ing",
			Meaning:      "present participle",
			Category:     WordCategoryAdjective,
			Productivity: 0.95,
			Examples:     []string{"running", "pending", "processing"},
		},
		"ful": {
			Suffix:       "ful",
			Meaning:      "full of, having",
			Category:     WordCategoryAdjective,
			Productivity: 0.8,
			Examples:     []string{"successful", "powerful", "useful"},
		},
		"less": {
			Suffix:       "less",
			Meaning:      "without",
			Category:     WordCategoryAdjective,
			Productivity: 0.85,
			Examples:     []string{"stateless", "endless", "wireless"},
		},
		"ous": {
			Suffix:       "ous",
			Meaning:      "having the quality of",
			Category:     WordCategoryAdjective,
			Productivity: 0.7,
			Examples:     []string{"synchronous", "anonymous", "continuous"},
		},
		"ive": {
			Suffix:       "ive",
			Meaning:      "having the nature of",
			Category:     WordCategoryAdjective,
			Productivity: 0.8,
			Examples:     []string{"active", "passive", "interactive"},
		},
		"al": {
			Suffix:       "al",
			Meaning:      "relating to",
			Category:     WordCategoryAdjective,
			Productivity: 0.85,
			Examples:     []string{"logical", "ational", "virtual"},
		},
		"ic": {
			Suffix:       "ic",
			Meaning:      "relating to",
			Category:     WordCategoryAdjective,
			Productivity: 0.8,
			Examples:     []string{"static", "dynamic", "atomic"},
		},
		// Verb-forming suffixes
		"ize": {
			Suffix:       "ize",
			Meaning:      "to make, to cause",
			Category:     WordCategoryVerb,
			Productivity: 0.85,
			Examples:     []string{"initialize", "optimize", "serialize"},
		},
		"ise": {
			Suffix:       "ise",
			Meaning:      "to make, to cause",
			Category:     WordCategoryVerb,
			Productivity: 0.8,
			Examples:     []string{"normalise", "standardise", "synchronise"},
		},
		"fy": {
			Suffix:       "fy",
			Meaning:      "to make, to cause",
			Category:     WordCategoryVerb,
			Productivity: 0.75,
			Examples:     []string{"verify", "modify", "classify"},
		},
		"ate": {
			Suffix:       "ate",
			Meaning:      "to make, to cause",
			Category:     WordCategoryVerb,
			Productivity: 0.8,
			Examples:     []string{"validate", "generate", "calculate"},
		},
		// Adverb-forming suffixes
		"ly": {
			Suffix:       "ly",
			Meaning:      "in a manner",
			Category:     WordCategoryAdverb,
			Productivity: 0.95,
			Examples:     []string{"quickly", "safely", "efficiently"},
		},
		"ward": {
			Suffix:       "ward",
			Meaning:      "in direction of",
			Category:     WordCategoryAdverb,
			Productivity: 0.6,
			Examples:     []string{"forward", "backward", "inward"},
		},
		"wise": {
			Suffix:       "wise",
			Meaning:      "in the manner of",
			Category:     WordCategoryAdverb,
			Productivity: 0.5,
			Examples:     []string{"likewise", "otherwise", "clockwise"},
		},
	}
	
	e.suffixDB = suffixes
}

// loadRootWordDatabase initializes the root word database with common English roots and programming terms
func (e *MorphologyEngine) loadRootWordDatabase() {
	roots := map[string]RootInfo{
		// Common English roots with high frequency
		"work": {
			Word:       "work",
			Frequency:  8500,
			Category:   WordCategoryVerb,
			Variations: []string{"worker", "working", "worked"},
			IsTechnical: false,
		},
		"hand": {
			Word:       "hand",
			Frequency:  7200,
			Category:   WordCategoryNoun,
			Variations: []string{"handle", "handler", "handling"},
			IsTechnical: true,
		},
		"manage": {
			Word:       "manage",
			Frequency:  6800,
			Category:   WordCategoryVerb,
			Variations: []string{"manager", "management", "managing"},
			IsTechnical: true,
		},
		"process": {
			Word:       "process",
			Frequency:  9200,
			Category:   WordCategoryNoun,
			Variations: []string{"processor", "processing", "processed"},
			IsTechnical: true,
		},
		"serve": {
			Word:       "serve",
			Frequency:  5400,
			Category:   WordCategoryVerb,
			Variations: []string{"server", "service", "serving"},
			IsTechnical: true,
		},
		"connect": {
			Word:       "connect",
			Frequency:  4800,
			Category:   WordCategoryVerb,
			Variations: []string{"connection", "connector", "connected"},
			IsTechnical: true,
		},
		"data": {
			Word:       "data",
			Frequency:  8900,
			Category:   WordCategoryNoun,
			Variations: []string{"database", "dataset", "datatype"},
			IsTechnical: true,
		},
		"base": {
			Word:       "base",
			Frequency:  6100,
			Category:   WordCategoryNoun,
			Variations: []string{"basic", "baseline", "based"},
			IsTechnical: true,
		},
		"valid": {
			Word:       "valid",
			Frequency:  3200,
			Category:   WordCategoryAdjective,
			Variations: []string{"validate", "validation", "validator"},
			IsTechnical: true,
		},
		"config": {
			Word:       "config",
			Frequency:  2800,
			Category:   WordCategoryNoun,
			Variations: []string{"configure", "configuration", "configured"},
			IsTechnical: true,
		},
		"execute": {
			Word:       "execute",
			Frequency:  3600,
			Category:   WordCategoryVerb,
			Variations: []string{"executor", "execution", "executable"},
			IsTechnical: true,
		},
		"generate": {
			Word:       "generate",
			Frequency:  4200,
			Category:   WordCategoryVerb,
			Variations: []string{"generator", "generation", "generated"},
			IsTechnical: true,
		},
		"calculate": {
			Word:       "calculate",
			Frequency:  3800,
			Category:   WordCategoryVerb,
			Variations: []string{"calculator", "calculation", "calculated"},
			IsTechnical: true,
		},
		"transform": {
			Word:       "transform",
			Frequency:  3400,
			Category:   WordCategoryVerb,
			Variations: []string{"transformer", "transformation", "transformed"},
			IsTechnical: true,
		},
		"parse": {
			Word:       "parse",
			Frequency:  2600,
			Category:   WordCategoryVerb,
			Variations: []string{"parser", "parsing", "parsed"},
			IsTechnical: true,
		},
		"format": {
			Word:       "format",
			Frequency:  4600,
			Category:   WordCategoryNoun,
			Variations: []string{"formatter", "formatting", "formatted"},
			IsTechnical: true,
		},
		"encode": {
			Word:       "encode",
			Frequency:  2200,
			Category:   WordCategoryVerb,
			Variations: []string{"encoder", "encoding", "encoded"},
			IsTechnical: true,
		},
		"decode": {
			Word:       "decode",
			Frequency:  1800,
			Category:   WordCategoryVerb,
			Variations: []string{"decoder", "decoding", "decoded"},
			IsTechnical: true,
		},
		"serialize": {
			Word:       "serialize",
			Frequency:  1500,
			Category:   WordCategoryVerb,
			Variations: []string{"serializer", "serialization", "serialized"},
			IsTechnical: true,
		},
		"initialize": {
			Word:       "initialize",
			Frequency:  2400,
			Category:   WordCategoryVerb,
			Variations: []string{"initializer", "initialization", "initialized"},
			IsTechnical: true,
		},
		"optimize": {
			Word:       "optimize",
			Frequency:  2100,
			Category:   WordCategoryVerb,
			Variations: []string{"optimizer", "optimization", "optimized"},
			IsTechnical: true,
		},
		"cache": {
			Word:       "cache",
			Frequency:  2800,
			Category:   WordCategoryNoun,
			Variations: []string{"cached", "caching", "cacheable"},
			IsTechnical: true,
		},
		"request": {
			Word:       "request",
			Frequency:  5200,
			Category:   WordCategoryNoun,
			Variations: []string{"requesting", "requested", "requester"},
			IsTechnical: true,
		},
		"response": {
			Word:       "response",
			Frequency:  4800,
			Category:   WordCategoryNoun,
			Variations: []string{"responding", "responded", "responder"},
			IsTechnical: true,
		},
		"session": {
			Word:       "session",
			Frequency:  3600,
			Category:   WordCategoryNoun,
			Variations: []string{"sessions", "sessional", "sessioned"},
			IsTechnical: true,
		},
		"interface": {
			Word:       "interface",
			Frequency:  4200,
			Category:   WordCategoryNoun,
			Variations: []string{"interfaces", "interfaced", "interfacing"},
			IsTechnical: true,
		},
		"implement": {
			Word:       "implement",
			Frequency:  3800,
			Category:   WordCategoryVerb,
			Variations: []string{"implementation", "implemented", "implementing"},
			IsTechnical: true,
		},
		"method": {
			Word:       "method",
			Frequency:  6200,
			Category:   WordCategoryNoun,
			Variations: []string{"methods", "methodical", "methodology"},
			IsTechnical: true,
		},
		"function": {
			Word:       "function",
			Frequency:  7800,
			Category:   WordCategoryNoun,
			Variations: []string{"functional", "functionality", "functioning"},
			IsTechnical: true,
		},
		"parameter": {
			Word:       "parameter",
			Frequency:  2400,
			Category:   WordCategoryNoun,
			Variations: []string{"parameters", "parametric", "parameterized"},
			IsTechnical: true,
		},
		"argument": {
			Word:       "argument",
			Frequency:  2800,
			Category:   WordCategoryNoun,
			Variations: []string{"arguments", "argumentative", "argumentation"},
			IsTechnical: true,
		},
		"variable": {
			Word:       "variable",
			Frequency:  3400,
			Category:   WordCategoryNoun,
			Variations: []string{"variables", "variability", "variation"},
			IsTechnical: true,
		},
		"constant": {
			Word:       "constant",
			Frequency:  2600,
			Category:   WordCategoryNoun,
			Variations: []string{"constants", "constantly", "constancy"},
			IsTechnical: true,
		},
		"struct": {
			Word:       "struct",
			Frequency:  1800,
			Category:   WordCategoryNoun,
			Variations: []string{"structure", "structured", "structuring"},
			IsTechnical: true,
		},
		"class": {
			Word:       "class",
			Frequency:  5600,
			Category:   WordCategoryNoun,
			Variations: []string{"classes", "classify", "classification"},
			IsTechnical: true,
		},
		"object": {
			Word:       "object",
			Frequency:  6800,
			Category:   WordCategoryNoun,
			Variations: []string{"objects", "objective", "objection"},
			IsTechnical: true,
		},
		"instance": {
			Word:       "instance",
			Frequency:  3200,
			Category:   WordCategoryNoun,
			Variations: []string{"instances", "instantiate", "instantiation"},
			IsTechnical: true,
		},
		"context": {
			Word:       "context",
			Frequency:  4400,
			Category:   WordCategoryNoun,
			Variations: []string{"contexts", "contextual", "contextualize"},
			IsTechnical: true,
		},
		"client": {
			Word:       "client",
			Frequency:  4600,
			Category:   WordCategoryNoun,
			Variations: []string{"clients", "clientele", "clientside"},
			IsTechnical: true,
		},
		"protocol": {
			Word:       "protocol",
			Frequency:  2200,
			Category:   WordCategoryNoun,
			Variations: []string{"protocols", "protocoled", "protocoling"},
			IsTechnical: true,
		},
		"network": {
			Word:       "network",
			Frequency:  5400,
			Category:   WordCategoryNoun,
			Variations: []string{"networks", "networking", "networked"},
			IsTechnical: true,
		},
		"security": {
			Word:       "security",
			Frequency:  6200,
			Category:   WordCategoryNoun,
			Variations: []string{"secure", "secured", "securing"},
			IsTechnical: true,
		},
		"encrypt": {
			Word:       "encrypt",
			Frequency:  1600,
			Category:   WordCategoryVerb,
			Variations: []string{"encryption", "encrypted", "encrypting"},
			IsTechnical: true,
		},
		"decrypt": {
			Word:       "decrypt",
			Frequency:  1200,
			Category:   WordCategoryVerb,
			Variations: []string{"decryption", "decrypted", "decrypting"},
			IsTechnical: true,
		},
		"algorithm": {
			Word:       "algorithm",
			Frequency:  2800,
			Category:   WordCategoryNoun,
			Variations: []string{"algorithms", "algorithmic", "algorithmically"},
			IsTechnical: true,
		},
		"perform": {
			Word:       "perform",
			Frequency:  5800,
			Category:   WordCategoryVerb,
			Variations: []string{"performance", "performed", "performing"},
			IsTechnical: true,
		},
		"memory": {
			Word:       "memory",
			Frequency:  4200,
			Category:   WordCategoryNoun,
			Variations: []string{"memories", "memorize", "memorable"},
			IsTechnical: true,
		},
		"buffer": {
			Word:       "buffer",
			Frequency:  1800,
			Category:   WordCategoryNoun,
			Variations: []string{"buffers", "buffered", "buffering"},
			IsTechnical: true,
		},
		"stream": {
			Word:       "stream",
			Frequency:  2600,
			Category:   WordCategoryNoun,
			Variations: []string{"streams", "streaming", "streamed"},
			IsTechnical: true,
		},
		"thread": {
			Word:       "thread",
			Frequency:  2200,
			Category:   WordCategoryNoun,
			Variations: []string{"threads", "threading", "threaded"},
			IsTechnical: true,
		},
		"concurrent": {
			Word:       "concurrent",
			Frequency:  1400,
			Category:   WordCategoryAdjective,
			Variations: []string{"concurrency", "concurrently", "concurrents"},
			IsTechnical: true,
		},
		"synchronize": {
			Word:       "synchronize",
			Frequency:  1600,
			Category:   WordCategoryVerb,
			Variations: []string{"synchronous", "synchronization", "synchronized"},
			IsTechnical: true,
		},
		"asynchronous": {
			Word:       "asynchronous",
			Frequency:  1200,
			Category:   WordCategoryAdjective,
			Variations: []string{"asynchronously", "async", "asyncs"},
			IsTechnical: true,
		},
	}
	
	e.rootWordDB = roots
}